MODULE = ndn-lite

DIRS += encode face forwarder security app-support util
DIRS += encode/trust-schema
DIRS += security/default-backend
DIRS += security/default-backend/sec-lib/micro-ecc
DIRS += security/default-backend/sec-lib/tinycrypt

include $(RIOTBASE)/Makefile.base
